% Add Java jar files to the class path.
TOOLBOX_HOME = fileparts(which('tc_sample'));
packages = fullfile(TOOLBOX_HOME,'lib', ...
    {'blaise.jar', ...
    'bayesphys.jar', ...
    'trove.jar', ...
    'colt-free.jar'});

javaclasspath(packages);

