% Add Java jar files to the class path.

TOOLBOX_HOME = extractBefore(which('bayesPhys.tc_sample'),'+bayesPhys');
packages = fullfile(TOOLBOX_HOME,'lib', ...
    {'blaise.jar', ...
    'bayesphys.jar', ...
    'trove.jar', ...
    'colt-free.jar'});

javaclasspath(packages);

